### ISSUE TITLE
Vector and Matrix 

### ISSUE THREAD

**Issue by waynelapierre** [extendr/rextendr#10]
Is there any documentation about writing Rust functions with vector and matrix as inputs/outputs? I am currently using Rcpp's NumericVector and NumericMatrix.

**Comment by clauswilke** [comment]
Sorry, not at this time, as far as I'm aware. In any case, it would live with the documentation for the extendr crate, so you may want to file an issue there: https://github.com/extendr/extendr

**Comment by andy-thomason** [comment]
There is limited support for `ndarray` as a feature (you need to enable it in the toml file).

As yet, there is little documentation on this.

I have been planning to add row and column iterator support to matrices and there are functions like
`is_matrix` and `nrows`, `ncols` in the Robj implementation.

Documentation will improve sharply with our next major release, 0.2.0.

**Comment by clauswilke** [comment]
I don't see anything about `ndarray` in the development documentation. Do we need to build the docs with `--all-features`? (See https://doc.rust-lang.org/cargo/commands/cargo-doc.html#feature-selection)

The current build command is here:
https://github.com/extendr/extendr/blob/1d0999e71dc7896f0132db395f605f4b6cbd0db7/.github/workflows/docs.yml#L19

cc @yutannihilation

**Comment by yutannihilation** [comment]
Oh, good catch, thanks.

I got this error on my local on trying `cargo doc --all-features`. Is something wrong with my setup...?

```
error[E0106]: missing lifetime specifier
  --> extendr-api/src/robj_ndarray.rs:14:24
   |
14 |     Robj: AsTypedSlice<T>,
   |                        ^ expected named lifetime parameter
   |
help: consider using the `'a` lifetime
   |
14 |     Robj: AsTypedSlice<'a, T>,
   |                        ^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0106`.
error: could not document `extendr-api`
```

**Comment by clauswilke** [comment]
No, this looks like an error in the code. The compiler suggests the fix. Not sure why this didn't show up before.

**Comment by waynelapierre** [comment]
ndarray-stats contain a lot of useful functions. It would be great if extendr could add full support for ndarray.
