### ISSUE TITLE
Lean on withr

### ISSUE THREAD

**Issue by malcolmbarrett** [extendr/rextendr#109]
#106 adds withr to imports, so I'd like to lean on it for some of its state-management functions in place of `on.exit()` and friends.

**Comment by Ilia-Kosenkov** [comment]
@malcolmbarrett, please avoid this fragment for now
https://github.com/extendr/rextendr/blob/5ee2062d9134084a99e68266271985e360244d6e/R/source.R#L223-L233
I have a PR ready that improves rtools detection and uses {withr} instead of `on.exit` in `invoke_cargo` function.

**Comment by malcolmbarrett** [comment]
Got it, thanks!
