### ISSUE TITLE
Set CARGO_HOME in Makevars

### ISSUE THREAD

**Issue by yutannihilation** [extendr/rextendr#133]
I got this review comment from CRAN:

> Checking this creates ~/.cargo sized 82MB, in violation of the CRAN Policy.
> Please fix as necessary and resubmit.

It seems we need to set `CARGO_HOME` to somewhere inside package directory and delete the cache after installation.

c.f. https://github.com/r-rust/gifski/blob/6b86cc6b60abbc2294db821f27cae37413df70c2/src/Makevars#L9

**Comment by CGMossa** [comment]
Is this *still* the case?

**Comment by yutannihilation** [comment]
What do you mean? The CRAN Policy is still there.

**Comment by yutannihilation** [comment]
Seems already resolved by https://github.com/extendr/rextendr/pull/233
