### ISSUE TITLE
Enable optional `ucrt` support on Windows

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/rextendr#137]
In short, new Rtools and `R` starting with `4.2.0` (or maybe later) will support `ucrt` Windows toolchain. It is already part of Rtools that we use.
`R` built for `ucrt` (instead of `mingw`) has better support for `UTF-8` (basically, it works, while before it was a nightmare). So, packages have to be compiled using `ucrt` toolchain as well.

When building a package, the toolchain is configured by the environment (see discussion [here](https://github.com/extendr/libR-sys/issues/79)), but when we compile rust code dynamically, we inject Rtools to the path here:
https://github.com/extendr/rextendr/blob/31c3cd331b0923f17da22c0f27d2168c2014f1e7/R/source.R#L223-L280

We propose to modify `use_rtools` parameter, make it an enum, accepting the following values: `"none", "mingw", "ucrt"`, defaulting to `mingw`. This will allow to compile Rust code using new toolchain by specifying this argument. We can potentially rename the parameter to `use_rtools_version`, so it reads better( e.g. `some_fun(..., use_rtools_version = "ucrt")`).
It is still unclear (to me) what happens if we compile a library using `mingw` toolchain and then `dyn.load` it in `R` built with `ucrt`, but I'd prefer to have the switch available (both `mingw` and `ucrt` toolchains are distributed together, so there is no standard way to install only one of them).

**Comment by yutannihilation** [comment]
I think the UCRT toolchain is fully supported now. Closing this.

**Comment by CGMossa** [comment]
Amazing. I'm beyond impressed with this.
