### ISSUE TITLE
edition = "2021"

### ISSUE THREAD

**Issue by yutannihilation** [extendr/rextendr#143]
The nightly cargo already specifies `edition = "2021"` by default, and it will be shipped in Rust 1.56.

https://github.com/extendr/rextendr/blob/9b2f49519b7b86a5b31f8ad20cd652566d43c498/R/source.R#L313

**Comment by yutannihilation** [comment]
Now Rust 1.56 is released. However, is it really possible to make edition 2021 our default in a foreseeable future? Can we expect the CRAN Linux machines update their toolchain? The Debian machines are testing, so it might be updated eventually, but the version of Fedora is fixed at 32.

**Comment by Ilia-Kosenkov** [comment]
We can specify `edition` here https://github.com/extendr/rextendr/blob/68fc6154440a1dcfb3d88dafee7bcc6238626188/R/use_extendr.R#L18 as a parameter,  and make it default to 2021. 
According to [this](https://doc.rust-lang.org/book/appendix-05-editions.html),
<details>
<summary>we can mix editions.</summary>
All Rust compiler versions support any edition that existed prior to that compiler’s release, and they can link crates of any supported editions together. Edition changes only affect the way the compiler initially parses code. Therefore, if you’re using Rust 2015 and one of your dependencies uses Rust 2018, your project will compile and be able to use that dependency. The opposite situation, where your project uses Rust 2018 and a dependency uses Rust 2015, works as well.
</details>

So we can probably specify edition as `function(..., edition = c("2021", "2018", "2015"))` and use something like [`match.arg`](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/match.arg) to resolve it to one of the allowed values.

**Comment by yutannihilation** [comment]
Yes, we can mix the 2021 edition with older ones as long as the Rust version is >= 1.56. I bet it's 99% true on the developers' local environment, but the CRAN machines might not be that modern. So, if the main target of rextendr is CRAN-ready packages, we might need to wait for a while until the CRAN machines get ready. GitHub-only packages have no problem.

**Comment by CGMossa** [comment]
Closing this issue as it was resolved with #195.
