### ISSUE TITLE
Allow passing `...` from `rextendr::document` into `devtools::document`

### ISSUE THREAD

**Issue by multimeric** [extendr/rextendr#153]
I've been hitting an issue where, when I run `rextendr::document()`, I get:

```
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
  must specify DLL via a “DLLInfo” object. See getLoadedDLLs()
```

This issue is caused by roxygen, and has a long discussion [here](https://github.com/r-lib/roxygen2/issues/822). The short solution is to simply use [`roxygenise(load = "source")`](https://github.com/r-lib/roxygen2/issues/822#issuecomment-533183162). 

However, I can't use this `load` argument with `rextendr::document`. It would be nice if I could, for this reason. We could just forward all additional arguments to the underlying documentation function.

**Comment by clauswilke** [comment]
Sounds reasonable. Feel free to submit a PR.

**Comment by multimeric** [comment]
Ah, actually this would require using `roxygen::roxygenize()` as the underlying function, which is a bit trickier because we would lose all the nice `devtools` info messages.

**Comment by Ilia-Kosenkov** [comment]
@multimeric, is it still a major problem? `devtools::document()` internally calls `roxygen::roxygenize()`, so in principle we can duplicate the logic of `devtools::document()` , but I am not a fan of this solution.

**Comment by Ilia-Kosenkov** [comment]
I will close this since `rextendr::document()` is designed to closely follow `devtools::document()`.
