### ISSUE TITLE
Generate `NULL` or `missing_arg()` defaults for Rust function with `Option<T>` argument

### ISSUE THREAD

**Issue by multimeric** [extendr/rextendr#154]
I have a Rust function which has the signature:

```rust
fn some_func(data: ArrayView2<f64>, threads: Option<i32>) -> List {}
```

When I ` rextendr::document()`, the resulting R wrapper is:

```r
some_func <- function(data, threads) {}
```

Obviously in Rust there is no way of avoiding providing all arguments, but in R this is not idiomatic. I suspect there is a conversion trait somewhere in `extendr` to convert from `NULL` in R to `None()` in Rust. If this is the case, could we generate a wrapper that therefore defaults to `NULL` for these `Option` arguments, to provide a nicer API? e.g. 

```r
some_func <- function(data, threads = NULL) {}
```

**Comment by multimeric** [comment]
> A good idea but right now we treat Option<i32> as i32 | NA_integer_ and disallow NULL.

Okay, if we have this mapping, then can't we simply generate an R wrapper that passes NA in this case? e.g. 

```r
some_func <- function(data, threads = NA_integer_) {}
```

Because that would work with my Rust code and also provide the R API that I'm after.

**Comment by Ilia-Kosenkov** [comment]
In this case I think we can, we only need someone to do it :-)

**Comment by multimeric** [comment]
I'm happy to do it, especially if it's that simple. Just making sure it's approved by you guys.

**Comment by Ilia-Kosenkov** [comment]
My only concern is whether we should make it a default behaviour. This should be indeed discussed.

**Comment by andy-thomason** [comment]
We do have a `Nullable` wrapper for things that may be NULL but we should consider
changing Option to accept/give NULL instead of NA.

**Comment by multimeric** [comment]
But will using `Nullable` result in R functions with default values? That's all I'm after.

**Comment by andy-thomason** [comment]
Ah, I see! At present, the wrapper generator is not affected by the type, we also could add an attribute
to make it explicit.

```
fn some_func(data: ArrayView2<f64>, #[default="NULL"] threads: Option<i32>) -> List {}
```

Does this work for you?

**Comment by andy-thomason** [comment]
We would need to add the default string (which is R source code) to `Arg`:

https://github.com/extendr/extendr/blob/master/extendr-api/src/metadata.rs#L10-L14

The default value would be added here:

https://github.com/extendr/extendr/blob/master/extendr-api/src/metadata.rs#L133

**Comment by andy-thomason** [comment]
@Ilia-Kosenkov  I can do this if you like, or would you like to try?

**Comment by multimeric** [comment]
Oh, yes if you can do that. I didn't even know you could add attributes to single parameters. This would neatly bypass the issue of "how do we know if the R function should have a default value", because there might be cases where the Rust function accepts an optional arg but the R function still requires it to be explicitly passed.

**Comment by andy-thomason** [comment]
You can add attributes to pretty much all parts of the Rust AST. `syn` is a very handy library.

I'll raise a PR for this.

**Comment by clauswilke** [comment]
> My only concern is whether we should make it a default behaviour. This should be indeed discussed.

If I understand correctly, the general principle here would be to add the possibility of having default values on the R wrapper side. That sounds like a useful feature to have, but it should be customizable and work for any variable and data type.

**Comment by Ilia-Kosenkov** [comment]
@andy-thomason, I'd prefer you to work on this, macros are not my strong side. I had no idea Rust can have attributes on parameters, I am 100% for having attributes for default value generation.

**Comment by andy-thomason** [comment]
This provides defaults for functions, but we need to add a bit of work to extend the #[extendr] attribute to methods.

https://github.com/extendr/extendr/pull/334

**Comment by andy-thomason** [comment]
We now have the ability to use `#[default="xyz"]` on arguments.

Check to see if this fixes the issue.

**Comment by multimeric** [comment]
I'm not directly using this feature at the moment because I'm making my own custom R classes, but if this works like how I think, it will be super useful, and I'm happy to close.
