### ISSUE TITLE
Fix pkgdown build

### ISSUE THREAD

**Issue by yutannihilation** [extendr/rextendr#158]
```
Error: Error: Topics missing from index: rextendr
```
https://github.com/extendr/rextendr/actions/runs/1576733042

**Comment by Ilia-Kosenkov** [comment]
Something related to https://github.com/r-lib/pkgdown/issues/1132?

**Comment by yutannihilation** [comment]
pkgdown has been getting stricter about missing topics, so I guess this is what we need to fix on our side. We have two choices.

We can mark the topic as internal.

> We recommend placing package documentation in `{pkgname}-package.R`, and have `@keywords internal`.   
(<https://roxygen2.r-lib.org/articles/rd.html#packages>)

Or, we can make it internal in `_pkgdown.yml`

> pkgdown will warn if there are (non-internal) topics that not listed in the reference index. You can suppress these warnings by listing the topics in section with "title: internal" (case sensitive) which will not be displayed on the reference index. 
 (<https://pkgdown.r-lib.org/reference/build_reference.html?q=missing#missing-topics>)

Do you have any preference on this? If not, I'll go with the former one.
