### ISSUE TITLE
0.3.0

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/rextendr#185]
I have created a new [milestone](https://github.com/extendr/rextendr/milestone/2) to track progress towards the new release. 
I gathered the most important issues that we need to fix before trying new submission.
I have prototypes for some of the largest problems already in place (but no PRs yet), so I hope we can address everything soon.

We are open to suggestions and the milestone can be updated. I may have missed something important or included unnecessary features. Feel free to comment.

**Comment by Ilia-Kosenkov** [comment]
We have addressed the main issues I included into the `0.3.0` milestone. `{rextendr}` is now in a much better place. With that in mind, I believe it is time for a release. I have never released anything to CRAN, so I'd appreciate some help & guidance (looking at you @yutannihilation since you made a lot of submissions recently :-) )
Also pinging @CGMossa & @multimeric

**Comment by JosiahParry** [comment]
Given the number of dependencies this package has as well as suggestions. I strongly recommend using the R-CMD-check-hard GHA. I was bit super hard by this a few months ago because of a recursive suggested dependency not being available appropriately. 
https://github.com/tidymodels/spatialsample/actions/workflows/R-CMD-check-hard.yaml

**Comment by malcolmbarrett** [comment]
Another tool that will help head off any issues before submitting is `usethis::use_release_issue()`

**Comment by yutannihilation** [comment]
Yeah, you can just fill the TODO list of `usethis::use_release_issue()`. Take it easy, while CRAN might not always be easy.

One thing you should be aware is that the current maintainer of the package on CRAN is not you. I've never experienced this, but probably an email will be sent to Claus for approval when you submit a package. So, before submitting. you should notify him when you are ready.

**Comment by Ilia-Kosenkov** [comment]
Issue created https://github.com/extendr/rextendr/issues/277

**Comment by Ilia-Kosenkov** [comment]
Hey @clauswilke , it's been a while, but we are now in a better spot & are getting ready to push a new version of `{rextendr}` to CRAN. This is the first time we are doing it since you passed the responsibility to me, so there will be some back&forth between us and CRAN to convince them this is a legitimate submission. 
Issue #277 tracks the usual list of actions that we should take before submission
PR #280 brings some final cleanup (docs/news, etc).

**Comment by clauswilke** [comment]
No worries. They'll just send me an email where I have to confirm that you're the new maintainer. Should be easy.

**Comment by andy-thomason** [comment]
This is excellent work. If we can get this new submission in soon, we can include it in the interview I did with
the R foundation.

The R foundation suggested we submit a Sigplan paper.

**Comment by CGMossa** [comment]
@extendr/rextendr pinging everyone, as this could be a good way to ask this. I'd like to lead the efforts to write and publish a paper on ExtendR. I'll post on the other teams related on this as well before doing anything.

**Comment by Ilia-Kosenkov** [comment]
Initiating submission right now

**Comment by Ilia-Kosenkov** [comment]
And we are on [CRAN](https://cran.r-project.org/web/packages/rextendr/index.html). There are things I need to do after CRAN acceptance (namely github release). I will do this in the evening today. Thank you everyone!

**Comment by Ilia-Kosenkov** [comment]
The full release is done (this includes all CRAN & GitHub ceremonies). Fyi @andy-thomason
