### ISSUE TITLE
Mention alternatives in README

### ISSUE THREAD

**Issue by Robinlovelace** [extendr/rextendr#188]
I just came across this alternative approach to developing R packages that use Rust code: https://github.com/dbdahl/cargo-framework 

It links to this project. Worth adding a link in the opposite direction (couldn't see a link to it and it seems pretty new so imagine many people not aware of it)?

And more broadly any ideas on similarities/differences? 

Context: have written a simple [R interface](https://github.com/dabreegster/odjitter/tree/main/r) to the [odjitter Rust crate](https://github.com/dabreegster/odjitter) using system calls but would like to use a proper framework for proper Rust (and I guess CRAN compliant, I doubt my heavy use of `system()` would be acceptable on CRAN but any comments on that welcome as it seems to work and would love to get it out there) interface.

**Comment by Robinlovelace** [comment]
> And more broadly any ideas on similarities/differences?

Partial response to this, just found the [following](https://arxiv.org/pdf/2108.07179.pdf), seems **cargo** aims to be leaner and perhaps more low level while `rextendr` does object translation.

![image](https://user-images.githubusercontent.com/1825120/165520643-361cf025-3d8c-4a5a-80c7-6e98f1cbe558.png)

**Comment by Ilia-Kosenkov** [comment]
Can you make a PR? Also, I like their docs, I should get back to working on rextendr issues so we can make next release and perhaps write a paper ourselves.

**Comment by Robinlovelace** [comment]
Heads-up @Ilia-Kosenkov, PR incoming: https://github.com/extendr/rextendr/pull/189
