### ISSUE TITLE
`x86_64-w64-mingw32.static.posix\bin/ld.exe` linker cannot handle large rust crates

### ISSUE THREAD

**Issue by sorhawell** [extendr/rextendr#211]
## problem:
The following error occours if compiling a big project with latest rextendr on windows:
`C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: error: export ordinal too large: 88000`

## issue
It seems the rtools42 gnu linker currently uses a [16bit enumeration of symbols (ordinal symbol table)](https://stackoverflow.com/questions/47135973/error-export-ordinal-too-large-104116). If using a large rust crate such as `polars` the compilation will fail for windows as this table is exceeded.

## Minimal reproducible example:
[I have made a minimal inclusion of `polars`in helloextendr to show the error here](https://github.com/sorhawell/helloextendr_big_windows/actions/runs/3413285972/jobs/5679824782)

## What I could google:
[one tried to solve the issue by moving back `mvsc` another needed to use `gnu/msys2`  but alledgely got by doing some mix msys2+mvsc compiling](https://users.rust-lang.org/t/export-ordinal-too-large-error-while-linking/74547/7)

[Some golang people have the same isssue and are discussion to limit the number of exported symbols](https://github.com/golang/go/issues/40795)

... and it seems the gophers found some kind of [ solution here](https://github.com/golang/go/issues/30674)

**Comment by Ilia-Kosenkov** [comment]
(Following discord discussion, a public summary)
This is an issue with linker. Other framework and tools face this problem as well, and there appears to be no one-fits-all solution. We will try to explore what we can do to solve it. Unfortunately, at this point no ETA.

**Comment by sorhawell** [comment]
something like this [patch-function](https://github.com/sorhawell/helloextendr_big_windows/blob/main/R/make_win_def.R) could be a candidate fix:

**Comment by sorhawell** [comment]
useful url-links to linker LD docs:

[win32 cygwin options](https://sourceware.org/binutils/docs/ld/WIN32.html)
[linker command options](https://sourceware.org/binutils/docs/ld/Options.html)

**Comment by sorhawell** [comment]
For the case of most rextendr project almost the same .def file can be used to solve the problem. Only change name of package:  [see this example]( https://github.com/sorhawell/minipolars/blob/main/src/minipolars-win.def)
