### ISSUE TITLE
Inconsistent licensing

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/rextendr#22]
The repository contains two `LICENSE` files:
- [LICENSE](https://github.com/extendr/rextendr/blob/main/LICENSE), which appears to be a placeholder
- [LICENSE.md](https://github.com/extendr/rextendr/blob/main/LICENSE.md), which seems to be a regular MIT license

This is confusing and does not allow GitHub to automatically pick up the repository license type.

**Comment by malcolmbarrett** [comment]
That's pretty standard in R packages. Per the R pkgs book: https://r-pkgs.org/license.html#key-files

**Comment by Ilia-Kosenkov** [comment]
Ok, no further questions.
