### ISSUE TITLE
Notify which version of `rextendr` the package was created with

### ISSUE THREAD

**Issue by eitsupi** [extendr/rextendr#222]
How about adding a field to the `DESCRIPTION` file to indicate the version of `rextendr`, like `roxygen2`? (r-lib/roxygen2#338)

https://github.com/extendr/rextendr/blob/ae38dfc0ffa3fef294fc97424c7c19580968a787/DESCRIPTION#L72

I think it is useful because the format of files that `rextendr` generates may be updated, such as #214.

**Comment by Ilia-Kosenkov** [comment]
Right now we are stuck at this dev version since I am too lazy to complete a couple of tasks before pushing `0.3.0` for publication. But I guess after `0.3.0` is published, it will be useful.
