### ISSUE TITLE
Bug in `{purrr}` v 1.0.0 prevents from running Windows CI

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/rextendr#223]
See e.g. https://github.com/r-lib/actions/issues/672

**Comment by Ilia-Kosenkov** [comment]
https://github.com/extendr/rextendr/actions/runs/3765649180/jobs/6443174955

**Comment by yutannihilation** [comment]
Since CRAN submission is closed from Dec 22 to Jan 5, this can be fixed a week later at the earliest. Let's forget and enjoy winter holidays :)

**Comment by yutannihilation** [comment]
Fixed now 🎉
