### ISSUE TITLE
`rust_source()`'s `features` argument seems to be misleading

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/rextendr#239]
See this https://github.com/extendr/extendr/issues/481#issuecomment-1435708706 issue for reference. 

Currently, any arguments passed to `features` simply produce a new `[feature]` block in `Cargo.toml`. While it may be useful (?) to some extent, we are talking here about dynamic compilation, which is unlikely to be a complex project.

Consumers, however, may treat `features` as `features = "ndarray"` enabling `extendr-api/ndarray`.

Proposed solutions:
- We drop `features` completely and rely on 
  ```extendr_deps = list(`extendr-api` = list(version = "*", features = array("ndarray", 1)))```, which is a mouthful, and even if documented properly, will be misused
- We keep `features` but instead we go into `extendr_deps`, find `extendr-api` and add `features` to an existing list of features (or create a new one). This should be a reliable thing that works even if `extendr_deps` is provided by the user.

Personally I prefer the latter, since in the majority of cases it will just simplify all the code to `rextendr::rust_source(code = code, features = c("ndarray", "graphics"))`. If we want to allow only selected features, we would have to keep `rextendr` in sync with any features introduced in `extendr`, which is a reasonable tradeoff for configuration safety.

**Comment by Ilia-Kosenkov** [comment]
I may be wrong since I do not recall why and how we added this `features` parameter. The issue is we pass it directly to `toml` while consumers (me including) expect that it is just a set of features that can be enabled for `extendr-api`. 
I am not even sure at this point that we need to allow writing to `Cargo.toml` directly.

It feels like we need an `extendr_features = c("ndarray", "serde", "graphics", "either", "whatever")` and a `use_dev_extendr = TRUE` parameters which will cover like all of the issues we get from people. 

And another parameter for `rust_function`, something like `extendr_attributes = list(use_try_from = TRUE)`. And that's it, all covered.

**Comment by CGMossa** [comment]
I agree.
The issue is compilation-time more than anything (to me).
For instance `serde` (with derive-feature) is costly on compilation.
But that's interesting perspective. `rextendr` should have opinionated
defaults, so
that people can use it out-of-the-box;

**Comment by multimeric** [comment]
Hmm, shouldn't enabling the `ndarray` feature on extendr also install the package as a dependency, making     `dependencies = list(`ndarray` = "*")` redundant? 

Still, it's not like we're providing a general serialization method even now, since the structure you pass into `rust_source` doesn't correspond to a `cargo.toml`. So I'm happy to make changes to make it even more user friendly.

**Comment by CGMossa** [comment]
Unless extendr reexports ndarray, then no, you still need `ndarray` as a
dependency if you are to use it in the intermediate crate.

**Comment by Ilia-Kosenkov** [comment]
Turns out it was me who incorrectly added `features` parameter. I guess it is up to me to fix it :)
