### ISSUE TITLE
Error in myextendr::hello_world() : object 'wrap__hello_world' not found

### ISSUE THREAD

**Issue by junjunlab** [extendr/rextendr#255]
Hi, I am creating an R package with example according to rextendr. But I got this error "**Error in myextendr::hello_world() : object 'wrap__hello_world' not found**" at last. How can I solve this error. Thanks!

**Comment by Ilia-Kosenkov** [comment]
Hi! It is hard to diagnose the problem based on what you wrote. Can you share the full example with us? E.g. the sequence of commands you executed.

**Comment by junjunlab** [comment]
Problem has been solved, thanks! By the way, how can I change rust hashmap into R list object with extendr, the following is my example incorrect code:

```
#[extendr]
fn get_hashmap() -> HashMap<String, f64> {
    let mut map = HashMap::new();
    map.insert("a".to_string(), 1.0);
    map.insert("b".to_string(), 2.0);
    map.insert("c".to_string(), 3.0);
    map
} 
```

**Comment by Ilia-Kosenkov** [comment]
It would be nice if you could still explain what was the original problem before we close the issue so in the future other developers can check it out before opening a new discussion.

**Comment by Ilia-Kosenkov** [comment]
Well, hashmaps do not preserve the order of the items. In fact, hashmaps can return items in a different order every time you re-start the application, so that is expected. Speaking of requirement to store `Robj` there, we need to check our trait bounds, I suspect you should be able to store any `T : IntoRobj` there.

**Comment by Qile0317** [comment]
> Hi! It is hard to diagnose the problem based on what you wrote. Can you share the full example with us? E.g. the sequence of commands you executed.

I'm also a new user, and I just simply followed the tutorial and very simply ran the following:
`library(rextendr)
rextendr::use_extendr()
rextendr::document()
hello_world()`

Everything printed in the R terminal before running `hello_world()` seemed normal, but running the function outputs the following error: `Error in hello_world() : object 'wrap__hello_world' not found`

**Comment by JosiahParry** [comment]
Can you try the following? I think you may need to `load_all()`
```r
rextendr::use_extendr()
rextendr::document()
devtools::load_all()
hello_world()
```

**Comment by Qile0317** [comment]
> Can you try the following? I think you may need to `load_all()`
> 
> ```r
> rextendr::use_extendr()
> rextendr::document()
> devtools::load_all()
> hello_world()
> ```

ah, worked perfectly, thank you!

**Comment by CGMossa** [comment]
First, `rextendr::use_extendr()` is to be used only once per package.
My experience `rexendr::document()` is all you need, but maybe I'm misunderstanding something.

Since everything is solved and everyone is happy, I'll close this.
