### ISSUE TITLE
*_dfr() suffixes in purr are superceded

### ISSUE THREAD

**Issue by JosiahParry** [extendr/rextendr#266]
As of purrr v 1.0.0 all `_dfr()` suffixes have been superceded. The recommendation now is to use `purrr::list_rbind()` after using `purrr::map()` though this would require setting a min version to `>= 1.0.0`--but since dplyr is imported I think `bind_rows()` can be used. 

See related https://github.com/extendr/rextendr/pull/263#discussion_r1174589745

This is not an urgent issue but may become a pain point if any issues are further introduced upstream in a later version of purrr.

**Comment by eitsupi** [comment]
FYI, the R version requirement for rextendr is more stringent than purrr 1.0.0 (4.0 v.s. 3.5), so I think the purrr version requirement is unlikely to be a problem.

**Comment by JosiahParry** [comment]
Also, as I understand it this only would impact the development of extendr packages. But packages developed with extendr don’t have this same version requirement. Is that right?

**Comment by eitsupi** [comment]
> Also, as I understand it this only would impact the development of extendr packages. But packages developed with extendr don’t have this same version requirement. Is that right?

Yes, packages created using rextendr have no dependency on rextendr.
