### ISSUE TITLE
Allow `rextendr::document()` to compile only

### ISSUE THREAD

**Issue by daniellga** [extendr/rextendr#276]
I am not using roxygen on my project but rextendr keeps changing my NAMESPACE and DESCRIPTION file. Is it possible to add an argument to allow only the compiling/recompiling functionalities to be used? Something like `rextendr::document(compile_only = TRUE)` or `rextendr::document(roxygenize = FALSE)`. Or even create a new function (`rextendr::compile()`, maybe?) with only the compiling part of `rextendr::document()`.

**Comment by Ilia-Kosenkov** [comment]
We rely on [`devtools::document()`](https://www.rdocumentation.org/packages/devtools/versions/2.4.5/topics/document). Do you know if you can achieve what you need by modifying `roclets` argument? If yes, it is an easy task, because we already forward `roclets` from `rextendr::document()` to `devtools::document()`.

**Comment by JosiahParry** [comment]
If you are inside of RStudio you can run CMD shift B to trigger a build and then CMD shift l to load all. That is the approach I take. Or you can even skip the build because devtools will recompile for you. Would that fit the bill?

**Comment by daniellga** [comment]
> We rely on [`devtools::document()`](https://www.rdocumentation.org/packages/devtools/versions/2.4.5/topics/document). Do you know if you can achieve what you need by modifying `roclets` argument? If yes, it is an easy task, because we already forward `roclets` from `rextendr::document()` to `devtools::document()`.

I already tried messing with this roclet thing to no avail. What would I put there to avoid having this behaviour?

![image](https://github.com/extendr/rextendr/assets/43149605/61af86fd-31c8-462c-9914-c193e778e4fc)

**Comment by JosiahParry** [comment]
Why do you need to use document? Can you use `register_extender()` instead?

**Comment by daniellga** [comment]
oh I didn't know about this function. Thanks!
