### ISSUE TITLE
Use wrappers generated by Rust library

### ISSUE THREAD

**Issue by clauswilke** [extendr/rextendr#28]
We should rewrite `rust_source()` so it uses the new wrapper code generated by the Rust library.

This requires restructuring things a little bit but there's no fundamental technical barrier as far as I can see.

After the rewrite, `rust_source()` will require the Rust code to include an `extendr_module!` macro call. For `rust_function()`, we can generate the module macro call automatically as needed.

**Comment by andy-thomason** [comment]
I was thinking of making a macro to wrap and export all the functions and impls in a source file,
possibly as an extension to `extendr_module!`.

This may be useful.
