### ISSUE TITLE
Use RSPM for package binaries 

### ISSUE THREAD

**Issue by JosiahParry** [extendr/rextendr#327]
https://github.com/extendr/rextendr/blob/09bfebae90e679cbb3a21e9ce983c032c82e1828/.github/workflows/R-CMD-check.yaml#L48C9-L48C9

Currently the GHA do not use binaries for ubuntu and are using source installation which is much much slower. To fix this we must add `use-public-rspm: true` into the yaml

for example: 

https://github.com/R-ArcGIS/arcpbf/blob/cddbd29e22f96106e2dce5463e63ad9123bed56a/.github/workflows/R-CMD-check.yaml#L36

**Comment by Ilia-Kosenkov** [comment]
Wasn't this resolved in a recent PR?

**Comment by JosiahParry** [comment]
Yes #336
