### ISSUE TITLE
Make module generation more robust

### ISSUE THREAD

**Issue by clauswilke** [extendr/rextendr#33]
The module generation code expects `#[extendr]` immediately in front of a function or impl declaration. It would be good to make it more robust, e.g., allow additional attributes between `#[extendr]` and the declaration.

Also possibly generate a warning of no `#[extendr]` attributes are found.

**Comment by Ilia-Kosenkov** [comment]
@clauswilke, I've got a prototype pseudo-parser that should better detect pairs of '#[extendr]` and `fn|impl` declarations.
We can achieve the following:
Take this (valid) Rust code with lots of weird declarations:
<details>
<summary>Rust</summary>

```Rust
#[extendr]fn test_fn_1() {}


#[extendr]
#[allow(dead_code)]
fn test_fn_2() {
  // Comment #1
  let _ = (); // Comment #2
  // Comment #3

}


#[allow(dead_code)]
                      //
//
//
#[extendr]
//
//
//
fn 
test_fn_3() {}

#[extendr]
/*
multiline comment
2 /*
3
4
5
6*/ /*
*/
*/

/*/*/**/*/*/
fn test_fn_4(){}

#[extendr]
fn test_fun/*comment in declaration*/(){}

struct X<'a> {
  field: &'a str
}

#[extendr/*with a comment*/]
impl<'a> X<'a> {
  
}

```
</details>

Clean it into
<details>
<summary>Comment- and emptyline- less Rust</summary>

```R
 [1] "#[extendr]fn test_fn_1() {}"
 [2] "#[extendr]"
 [3] "#[allow(dead_code)]"
 [4] "fn test_fn_2() {"
 [5] "  let _ = (); "
 [6] "}"
 [7] "#[allow(dead_code)]"
 [8] "#[extendr]"
 [9] "fn "
[10] "test_fn_3() {}"
[11] "#[extendr]"
[12] "fn test_fn_4(){}"
[13] "#[extendr]"
[14] "fn test_fun                          (){}"
[15] "struct X<'a> {"
[16] "  field: &'a str"
[17] "}"
[18] "#[extendr                  ]"
[19] "impl<'a> X<'a> {"
[20] "}"
```
</details>

And parse it into metadata:

<details>
<summary>Metadata</summary>

```R
# A tibble: 6 x 3
  name      type  lifetime
  <chr>     <chr> <chr>
1 test_fn_1 fn    NA
2 test_fn_2 fn    NA
3 test_fn_3 fn    NA
4 test_fn_4 fn    NA
5 test_fun  fn    NA
6 X         impl  'a
```
</details>

As a byproduct, this algorithm can detect invalid attribute placement (though it won't emit a lot of useful information, no line numbers in the original source code).
Dependencies are: rlang, purrr, dplyr (with tibble), stringi, and `%>%` for better readibility.

If this sounds reasonable (and needed), I can draft a PR.

**Comment by andy-thomason** [comment]
If there is a problem with:

```
#[extendr]
#[other]
fn xxx() {
}
```
We should be able to fix it in the macro.

Note that doc strings are effectively attributes:

```
#[extendr]
/// doc
fn xxx() {
}
```

If you have some concrete examples of failures, I'll work through it.

**Comment by clauswilke** [comment]
@Ilia-Kosenkov Yes, go ahead.

@andy-thomason There's nothing to be fixed on the Rust side. We need to write our own Rust parser in R here so the R package can extract information about the Rust macros without having to talk to the Rust compiler.

**Comment by andy-thomason** [comment]
Excellent!
