### ISSUE TITLE
Add CRAN compliance article to pkgdown site

### ISSUE THREAD

**Issue by JosiahParry** [extendr/rextendr#331]
In my recent PR I added an article describing how to make a package CRAN compliant. It however is not included in the pkgdown site. I was under the impression that the pkgdown workflow would add it but it has not. 
What needs to be done to include it on the pkgdown site? 

https://github.com/extendr/rextendr/blob/main/vignettes/articles/cran-compliance.Rmd

**Comment by tanho63** [comment]
https://github.com/extendr/rextendr/blob/edc54762b57ee046407f38d50c19d7d0f5b30644/_pkgdown.yml#L3-L4
pkgdown's "dev-mode: auto" is on, so it checks the DESCRIPTION file and renders anything with 4-part version numbers under a subpath dev: https://extendr.github.io/rextendr/dev/articles/cran-compliance.html

_continues aimlessly wandering through various discord servers, bored_

**Comment by JosiahParry** [comment]
Oh nice!!!!!!!!!!!
