### ISSUE TITLE
Use `configure.ac`

### ISSUE THREAD

**Issue by JosiahParry** [extendr/rextendr#369]
See example here: https://github.com/R-ArcGIS/arcgisgeocode/blob/main/configure.ac
Use the an accompanying [`tools/generate-configures.sh`](https://github.com/R-ArcGIS/arcgisgeocode/blob/main/tools/generate-configures.sh)

This should also include a printing of `cargo --version` and `rustc --version`

**Comment by Ilia-Kosenkov** [comment]
Can you explain this a little bit more? Why do we need `generate-configures`?

**Comment by JosiahParry** [comment]
I have changed my stance on this. We should use an R script instead.
