### ISSUE TITLE
Github pages is outdated / not updated

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/rextendr#37]
I am not familiar with how this website is built, but I noticed that the home page (https://extendr.github.io/rextendr/index.html) displays incorrect results, in particular, the last chunk:
```Rust
rprintln!("Hello from Rust!");

let x = 5;
let y = 7;
let z = x*y;

z
#> NULL
```

Vignettes are built correctly though.

**Comment by clauswilke** [comment]
Thanks. The `README.Rmd` file needs to be reknitted, and then the website rebuilt with `pkgdown::build_site()`. Looks like I forgot to reknit.

**Comment by Ilia-Kosenkov** [comment]
@clauswilke,
Could you do that? 
I was afraid one of my changes broke `knitr` integration.
Is there a way to automate pkgdown rebuilds?

**Comment by malcolmbarrett** [comment]
Would a PR to automate the pkgdown site on GHA be helpful? I'd be happy to do so

**Comment by clauswilke** [comment]
@malcolmbarrett Yes, I think that would be helpful.

**Comment by clauswilke** [comment]
I just fixed the README: https://github.com/extendr/rextendr/blob/main/README.md
I haven't fixed the website yet.
