### ISSUE TITLE
use_crate fails when no features specified

### ISSUE THREAD

**Issue by JosiahParry** [extendr/rextendr#387]
This change broke the function. Looks like we might be missing a test for this. I installed the new version 

```
rextendr::use_crate("lazy-static")
Running cargo add lazy-static '--features ' '--optional false'
Error:
! ! System command 'cargo' failed
```

This is because `"--features "` is included in the vector that is passed to processx. `--features`

_Originally posted by @JosiahParry in https://github.com/extendr/rextendr/pull/361#discussion_r1764103981_

**Comment by CGMossa** [comment]
Fixes by #388 (thanks @kbvernon for both the PR, and for notifying me that this issue can now be closed)
