### ISSUE TITLE
`rextendr` fails installation on Windows and Ubuntu LTS for R 4.0.5 despite having the requirement R >= 4.0 in DESCRIPTION

### ISSUE THREAD

**Issue by kpagacz** [extendr/rextendr#395]
Here's a log from one of my Github workflows - https://github.com/kpagacz/tergo/actions/runs/11763650814/job/32767897640?pr=6. `rextendr` fails to parse. The environment info is all in the logs.

Edit: I also get the same parsing error on Ubuntu LTS 22 https://github.com/kpagacz/tergo/actions/runs/11763650814/job/32767898242?pr=6

**Comment by Ilia-Kosenkov** [comment]
Hey @kpagacz , good catch, an anonymous function declaration (an `R 4.1.0` feature) crept into one of our code blocks here https://github.com/extendr/rextendr/blob/ea68f4ef05fedb5d0d1966f1517fc6cfac9e0944/R/utils.R#L52 . Should be an easy fix.

**Comment by kpagacz** [comment]
Thanks a lot for addressing this so quickly!

**Comment by Ilia-Kosenkov** [comment]
Let us know if this helps. There might be other issues with older R versions.
