### ISSUE TITLE
Add a link to https://extendr.github.io/rextendr/

### ISSUE THREAD

**Issue by yutannihilation** [extendr/rextendr#40]
It seems there's no link to the pkgdown website. Can anyone add https://extendr.github.io/rextendr/ to the repository's description? (Or may I get the permission on this repo...?)

**Comment by clauswilke** [comment]
You should have write permission already. Do you need other permissions?

**Comment by yutannihilation** [comment]
Yes, I mean write permission is not enough to edit here.

![Screenshot_20210209-140822](https://user-images.githubusercontent.com/1978793/107318555-61258700-6ae0-11eb-8d63-0dd16f99c580.png)

**Comment by clauswilke** [comment]
Ah, I get it now. You should be able to now.

**Comment by yutannihilation** [comment]
Confirmed, thanks! I added the link.
