### ISSUE TITLE
Should we be saving files on user's behalf?

### ISSUE THREAD

**Issue by JosiahParry** [extendr/rextendr#404]
I just came across the function `try_save_all()` and noticed it is used in `rextendr::document()`.

This function saves all open files if possible. To me, this feels somewhat invasive and can lead to rextendr saving files that the user didn't intend to. 

Should we remove this function and expect users to save their files on their own?
https://github.com/extendr/rextendr/blob/3ee8ae305dc2e8d5c6b158c9493e6d4bc0f6d40c/R/try_save_all.R#L8

**Comment by Ilia-Kosenkov** [comment]
This was someone's (don't remember whose) desire to integrate with RStudio IIRC.

**Comment by JosiahParry** [comment]
@Ilia-Kosenkov are you okay with removing this function? If so, I can make a PR to yank it

**Comment by Ilia-Kosenkov** [comment]
I am not a fan of this function for sure so go ahead :)
