### ISSUE TITLE
Removing the dynamically generated library files

### ISSUE THREAD

**Issue by CGMossa** [extendr/rextendr#5]
While investigating #2, I found out that the `clean_build_dir` doesn't remove the `dll` (on Windows) as it is already in use.
In order to remove it, it has to be unloaded. 
I don't know when the contents of the temporary directory are dropped/unlinked/removed. 

I tried this:

```r
clean_build_dir <- function() {
  if (!is.null(the$shared_lib))
    dyn.unload(x = the$shared_lib)
  if (!is.null(the$build_dir)) {
    unlink(the$build_dir, recursive = TRUE, force = TRUE)
    the$build_dir <- NULL
  }
}
```

But this is not good, as it is called after the build is done, and the the R-session is unable to call, since the dll is deleted.

Any suggestions? Maybe this is a non-issue?

**Comment by clauswilke** [comment]
All temporary files are removed when the R session ends, I believe. Could you try whether this works on Windows? I guess on Windows this requires R to unload all DLLs first, before removing the temp files.

**Comment by CGMossa** [comment]
That's exactly what I did try to do. No, the temporary folder is not completely deleted -- the dll remains. Even after I restart R or exit Rstudio entirely.

**Comment by clauswilke** [comment]
Do the Rcpp or cpp11 packages have the same problem?

**Comment by clauswilke** [comment]
See here for a simple call to cpp11 `cpp_function()`, which uses very similar code to the one rextendr uses (I modeled rextendr after cpp11):
https://cran.r-project.org/web/packages/cpp11/vignettes/cpp11.html

**Comment by CGMossa** [comment]
There are multiple tests that adds "calls" to the exit procedure, see this one

```R
  tf <- tempfile(fileext = ".cpp")
  writeLines(
    "[[cpp11::register]]
    bool always_true() {
      return true;
    }
    ", tf)
  on.exit(unlink(tf))

  dll_info <- cpp_source(tf, clean = TRUE, quiet = TRUE)
  on.exit(dyn.unload(dll_info[["path"]]), add = TRUE)
```

The `on.exit` call is both on the generated source file and the generated lib-file.
But this stuff is not done anywhere, but the tests..

**Comment by CGMossa** [comment]
After running this above example, I still observe a remaining dll file even after I exit the r-session... I think this is a problem also present in `cpp11`...

**Comment by clauswilke** [comment]
Honestly, this is one of the reasons Windows systems tend to slowly corrupt over time. Some process holds on to a file handle, and then another process cannot clean up or write updated contents to a file, and before you know it you've got old or broken files all over the place. It's quite amazing that we're in 2020 and they still haven't fixed this issue.

In the code you copied, the dll gets deleted before it gets unloaded, and so on Windows that doesn't work. Unix systems don't care.

Regardless, I like the fact that `cpp_source()` returns information about the dll that was built. We should add something like this to `rust_source()` also. Feel free to take a stab at this.

**Comment by clauswilke** [comment]
Sorry, I was wrong. We're already doing exactly what `cpp_source()` does. It simply returns the result from `dyn.load()`, which we also do.
