### ISSUE TITLE
Suggesting or replicating usethis functions

### ISSUE THREAD

**Issue by malcolmbarrett** [extendr/rextendr#62]
I'm happy to see the emergence of usethis-style functions, e.g. #53 and #60. 

I always find it a bit strange, though, when usethis-style functions don't quite behave like usethis (e.g. the UI and other defaults). A simple example is using `message()` instead of `ui_*()` or cli.

One solution is to add usethis to Suggests. Another option is to create lighter-weight internal options using cli. 

I'd be happy to work on this if it seems like a good idea.

**Comment by clauswilke** [comment]
That's mostly just my ignorance. Feel free to change. I'd rather have a cli dependency than usethis dependency.

**Comment by malcolmbarrett** [comment]
Ok, I'll prep a PR exploring that. Thanks!

**Comment by Ilia-Kosenkov** [comment]
I just want to point out that here https://github.com/r-lib/usethis/issues/956 hadley recommends to use `{cli}` instead of `ui_*` (at least that's how I understand his message). I suggest to use `{cli}` (see some crude examples in #65).

**Comment by malcolmbarrett** [comment]
Oh, great that you're already planning to import cli. Yes, there's some nice guidance here for writing usethis-like ui: https://cli.r-lib.org/articles/usethis-ui.html. I think limiting to cli makes sense for this use case.

**Comment by Ilia-Kosenkov** [comment]
Please take into account this set of functions when adding {cli} support
https://github.com/extendr/rextendr/blob/main/R/ui.R

**Comment by malcolmbarrett** [comment]
Thanks! I had intended to that in this PR, so awesome 😎 

I might continue waiting on this until #88/#70 are resolved as that directly affects the approach for this small issue

**Comment by Ilia-Kosenkov** [comment]
@malcolmbarrett,
Should this be closed or are there any other features you think should be implemented?

**Comment by malcolmbarrett** [comment]
I've got one more PR coming surrounding the way templates are handled that will close this
