### ISSUE TITLE
Don't generate .Rd pages for internal functions

### ISSUE THREAD

**Issue by clauswilke** [extendr/rextendr#71]
A few internal functions are currently documented using roxygen2, so man pages are generated. I think we should turn off man page generation. This generally means replacing `#'` with `#` at the beginning of each line.

These are the cases I'm aware of:

https://github.com/extendr/rextendr/blob/74817048d578c640e77df740e1fa00071320a011/R/register_extendr.R#L85-L100

https://github.com/extendr/rextendr/blob/74817048d578c640e77df740e1fa00071320a011/R/register_extendr.R#L120-L126

**Comment by clauswilke** [comment]
Also:
https://github.com/extendr/rextendr/blob/74817048d578c640e77df740e1fa00071320a011/R/ui.R#L1-L90

**Comment by yutannihilation** [comment]
How about just replacing `@keywords internal` with `@noRd`?

**Comment by clauswilke** [comment]
Ah, I wasn't aware this existed. Sure, works for me.
