### ISSUE TITLE
Write vignette on how to create and update a package with extendr code

### ISSUE THREAD

**Issue by clauswilke** [extendr/rextendr#74]
We should write a vignette explaining the recommended workflow.

**Comment by dcnorris** [comment]
On the "show me, don't tell me" principle, I suggest making the package *self-documenting*, by including a sample compiled function documented in the recommended way, etc., ... **and** demonstrating that CRAN accepts such a package. Arguably, a CRAN release for `extendr` should coincide with a fully worked-out scheme for getting `extendr`-using packages smoothly accepted onto CRAN. The very fact that CRAN accepts such a self-documenting `extendr` would be the crucial test of its CRAN-keyness.

A v0.2-3 of my [precautionary](https://CRAN.R-project.org/package=precautionary) package, which uses `extendr`, is I think (pray) on the verge of acceptance after bushwhacking through a lengthy review by CRAN over the past few weeks. But still some aspects of the configuration seem unsatisfactory to me — especially the need for an R build script in `tools/` which I have adapted from `salso` (see [here](https://github.com/cran/salso/tree/master/tools)). Is there a better scheme based on GNU Autotools? If so, that's exactly the sort of thing that might be developed and included by way of self-documentation in a CRAN release of `extendr`. For the long haul, surely Rust ought to be as much an expected part of the R package build chain as C++ or Fortran. If so, then the ideal should be to accommodate the usual R build idioms as much as possible.

**Comment by dcnorris** [comment]
... apropos of which, see Q below posted on r-pkg-devel. You comments most welcome of course.
https://stat.ethz.ch/pipermail/r-package-devel/2021q2/006936.html
