### ISSUE TITLE
Document internal functions

### ISSUE THREAD

**Issue by clauswilke** [extendr/rextendr#75]
There are numerous internal functions that have little or no documentation. We should try to document each internal function with at least one sentence explaining what the function does, and a quick explanation of what the parameters do.

Examples (not exhaustive):
https://github.com/extendr/rextendr/blob/74817048d578c640e77df740e1fa00071320a011/R/clean_code.R#L1-L157

https://github.com/extendr/rextendr/blob/74817048d578c640e77df740e1fa00071320a011/R/find_exports.R#L1-L17

https://github.com/extendr/rextendr/blob/74817048d578c640e77df740e1fa00071320a011/R/knitr_engine.R#L21-L62

**Comment by Ilia-Kosenkov** [comment]
As we have adopted an approach to document internal functions with standard tags + `@noRd`, I suggest to close this issue.
