### ISSUE TITLE
`pretty_rel_path()` should work outside of a package

### ISSUE THREAD

**Issue by yutannihilation** [extendr/rextendr#79]
(Originally found here: https://github.com/extendr/extendr/pull/190#issuecomment-798998867)

Currently it assumes the package root can be found, but I guess it might not be available in the case of `rust_source()`.

https://github.com/extendr/rextendr/blob/74817048d578c640e77df740e1fa00071320a011/R/track_rust_source.R#L5-L7

**Comment by clauswilke** [comment]
The benefit of integration testing. I've added this to #68.

**Comment by clauswilke** [comment]
Since `pretty_rel_path` is only used for printing, it should simply return the original path if no package can be found. @Ilia-Kosenkov should be able to add this in #76.

**Comment by yutannihilation** [comment]
Sounds good.

**Comment by Ilia-Kosenkov** [comment]
See https://github.com/extendr/rextendr/issues/83#issuecomment-799689776

**Comment by clauswilke** [comment]
@Ilia-Kosenkov If you consider this issue addressed with #76, please go ahead and close.

**Comment by clauswilke** [comment]
This seems to work now.
