### ISSUE TITLE
Do not use `pretty_rel_path()` outside of the package directory

### ISSUE THREAD

**Issue by yutannihilation** [extendr/rextendr#83]
I found it's not very pretty when it's outside of the current package directory.

```
build directory: /tmp/RtmpOxoyTp/file758976b349de

    Updating crates.io index
   Compiling rextendr3 v0.0.1 (/tmp/RtmpOxoyTp/file758976b349de)
    Finished dev [unoptimized + debuginfo] target(s) in 2.51s
✓ Writting wrappers to '../../../../tmp/RtmpOxoyTp/file758976b349de/target/extendr_wrappers.R'.
```

**Comment by clauswilke** [comment]
Yeah, it's not pretty and not useful. The absolute path would be better here. In general, I prefer absolute paths as it helps me find things when debugging, but I'm Ok with the relative path within a package.

**Comment by Ilia-Kosenkov** [comment]
There is a fix to this (I think) in #76: it outputs absolute path if package root cannot be found.
What you observe is the current behavior in `main`: `fs::path_rel` creates a relative path to `"."`, hence this mess.

**Comment by Ilia-Kosenkov** [comment]
Using #76:
<details>
<summary>Windows</summary>

``` r
rextendr::rust_function("fn test_fn() -> &'static str { \"Hello world!\"}")
#> build directory: C:\Users\[redacted]\AppData\Local\Temp\RtmpquP6lm\file51ac6f62432a
#> v Writting wrappers to C:/Users/[redacted]/AppData/Local/Temp/RtmpquP6lm/file51ac6f62432a/target/extendr_wrappers.R.
test_fn()
#> [1] "Hello world!"
```

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


</details>

<details>
<summary>Ubuntu @ WSL2</summary>

``` r
rextendr::rust_function("fn test_fn() -> &'static str { \"Hello world!\"}")
#> build directory: /tmp/RtmpOj94s3/file5134b8a71b4
#> ✔ Writting wrappers to /tmp/RtmpOj94s3/file5134b8a71b4/target/extendr_wrappers.R.
test_fn()
#> [1] "Hello world!"
```

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


</details>

**Comment by clauswilke** [comment]
@Ilia-Kosenkov If you consider this issue addressed with #76, please go ahead and close.

**Comment by Ilia-Kosenkov** [comment]
@clauswilke, I believe so. Let us close it for now.

**Comment by yutannihilation** [comment]
Thanks for fixing!
