### ISSUE TITLE
Github actions stopped running?

### ISSUE THREAD

**Issue by clauswilke** [extendr/rextendr#86]
It looks like github actions have stopped running. Not sure why.

**Comment by clauswilke** [comment]
Actions are working again but there are random errors during the initial setup: https://github.com/extendr/rextendr/runs/2118335977?check_suite_focus=true

**Comment by yutannihilation** [comment]
I heard bintray is down now. It's horrible that we still see the name of the service that will sunset in 1.5 month, btw...

https://status.bintray.com/

**Comment by yutannihilation** [comment]
Let's consider merging this if Bintray will stay unstable.

https://github.com/extendr/rextendr/pull/87

**Comment by yutannihilation** [comment]
Seems resolved now.
