### ISSUE TITLE
Remove {devtools} dependency

### ISSUE THREAD

**Issue by clauswilke** [extendr/rextendr#90]
We should remove {devtools} from imports. It's a pretty heavy dependency, and we use it only to call {roxygen2}. We could do that directly.

See also: https://github.com/extendr/rextendr/issues/88#issuecomment-802625576

**Comment by clauswilke** [comment]
(We will need to list {devtools} in supports, then, but that's fine.}

**Comment by yutannihilation** [comment]
What about moving {devtools} to Suggest dependency and let `rextendr::document()` abort when {devtools} is not installed?

**Comment by clauswilke** [comment]
That works for me also.
