### ISSUE TITLE
Upgrade to testthat 3

### ISSUE THREAD

**Issue by malcolmbarrett** [extendr/rextendr#98]
testthat edition 3 requires that you opt-in. Since this project is young, I think it would be wise to do so now for the long-term health of the codebase. It's possible that will require some refactoring in the tests or code, but testthat 3 also comes with [some nice features](https://testthat.r-lib.org/articles/third-edition.html)

**Comment by clauswilke** [comment]
I have no strong opinion on this. If you'd like to prepare a PR please go ahead.
