### ISSUE TITLE
Update vignette to suggest `.Renviron` `PATH` solution

### ISSUE THREAD

**Issue by malcolmbarrett** [extendr/rextendr#99]
Adding, e.g., `PATH="~/.cargo/bin:${PATH}"` to your `.Renviron` file if rextendr/R can't find `cargo`, likely to here: 
 https://extendr.github.io/rextendr/articles/setting_up_rust.html

I'm filing an issue rather than a PR because I'm actually not sure how robust of a solution it is yet!

**Comment by clauswilke** [comment]
@malcolmbarrett I just checked, on my Mac I have that line in my `.bash_profile` instead of in my `.Renviron`. Have you tested this? Does that not work for you?

**Comment by malcolmbarrett** [comment]
That didn't work for me, nor did modifying other various profile files, including for `zsh`.

What finally works is using `$HOME` rather than `~`. Now my `.Renviron` has:

`PATH="${HOME}/.cargo/bin:${PATH}"`

Now everyone that needs to can find `cargo` from R: 

``` r
system("which cargo")
Sys.which("cargo")
#>                                    cargo 
#> "/Users/malcolmbarrett/.cargo/bin/cargo"
processx::run("which", "cargo")
#> $status
#> [1] 0
#> 
#> $stdout
#> [1] "/Users/malcolmbarrett/.cargo/bin/cargo\n"
#> 
#> $stderr
#> [1] ""
#> 
#> $timeout
#> [1] FALSE
```

TBH, I have no idea why this worked vs. `~`, since it seems like they evaluate to the same value, nor why `Sys.which()` and `processx::run()` required this but `system()` did not

**Comment by clauswilke** [comment]
Interesting! At least this is an easy solution. Also, looking back at my `.bash-profile`, I am actually using `$HOME` instead of `~`. So maybe that's why I've never had any issues.

**Comment by yutannihilation** [comment]
Thanks for the discovery. The expansion of `~` is tricky (e.g. <https://unix.stackexchange.com/a/373532>); it's the feature of the shell, so it needs to be evaluated on the shell, which doesn't automatically happen (spoiler: you'll probably realize this when you want to handle file paths on Rust's side).

If I understand correctly, `system()` simply invokes the shell command, so probably everything is evaluated on shell as usual. On the other hand, processx doing things very programmatically, so I guess it's users' responsibility to expand the `PATH` (it might be considered as a bug, but I'm not sure). No idea about `Sys.which()`, though.

Anyway, we can advice to the usual users, but we cannot to the CRAN machines, so I need to put `PATH` here and there (sorry for the delay...)

**Comment by yutannihilation** [comment]
@malcolmbarrett 
If you have time, could you check if #166 let you use `rust_function()` (with a warning) without setting `PATH` in your `~/.Renviron`?
